jenkinsci/trilead-ssh2

src/com/trilead/ssh2/crypto/SimpleDERReader.java, src/com/trilead/ssh2/signature/ECDSAKeyAlgorithm.java, src/com/trilead/ssh2/signature/KeyAlgorithmManager.java, test/com/trilead/ssh2/signature/ECDSAKeyAlgorithmTest.java
Trilead currently silently ignores any ECDSA public key entries found in known_hosts, doesn't support them for identifying a remote host, and can't use ECDSA keys in user public key authentication. This change provides this support, as well as various other commits to allow some abstraction and extension of provision of key types.
=> [Jenkins-42959] support ECDSA keys

src/com/trilead/ssh2/Connection.java, src/com/trilead/ssh2/KnownHosts.java, src/com/trilead/ssh2/crypto/CryptoWishList.java, src/com/trilead/ssh2/crypto/dh/DhExchange.java, src/com/trilead/ssh2/crypto/dh/DhGroupExchange.java, src/com/trilead/ssh2/crypto/digest/HMAC.java, src/com/trilead/ssh2/crypto/digest/HashForSSH2Types.java, src/com/trilead/ssh2/crypto/digest/JreMessageDigestWrapper.java, src/com/trilead/ssh2/crypto/digest/MAC.java, src/com/trilead/ssh2/crypto/digest/MD5.java, src/com/trilead/ssh2/crypto/digest/MessageMac.java, src/com/trilead/ssh2/crypto/digest/SHA1.java, src/com/trilead/ssh2/transport/KexManager.java, src/com/trilead/ssh2/transport/KexState.java
An alternative to #9 and #7  that reduces the number of classes under change and doesn't break binary compatibility.
=> [FIXED JENKINS-33021] Add support for SHA256 and SHA512 HMAC algorithms

src/com/trilead/ssh2/KnownHosts.java, test/com/trilead/ssh2/KnownHostsTest.java
Currently calling `KnownHosts.getPreferredServerHostkeyAlgorithmOrder(String)` always returns null since the initial `preferredAlgo` variable is set to null and never updated. This prevents this method being any use for identifying preferred algorithms to use for the likes of JENKINS-42959.
Probably a good idea to merge #10 first to allow tests to be executed
=> [JENKINS-42959] Return host algorithms if in known_host and we support them

src/com/trilead/ssh2/DHGexParameters.java
Older versions of OpenSSH (verified against OpenSSH_5.9) do not correctly expand the key so drop the connection with a message similar to `fatal: dh_gen_key: group too small: 1024 (2*need 1024) [preauth]`. This change forces Trilead to generate a key at least 2048 bits in length to overcome this key expansion issue.
=> [JENKINS-43979] Fix OpenSSH dropping connections with SHA512 enabled

src/com/trilead/ssh2/KnownHosts.java, test/com/trilead/ssh2/KnownHostsTest.java
The known hosts key check is currently comparing the wrong fields whilst trying to find an algorithm to parse the current key - it should be checking the key format but is checking the key contents. This change fixes the comparison and adds a test to prevent future regression.
@paladox and @jenkinsci/code-reviewers
=> [JENKINS-42959] Correctly check host key algorithm

src/com/trilead/ssh2/transport/KexManager.java
Trilead currently tries to read a sub-field of the field it's trying to set whilst creating the Key Exchange Parameters for diffie-hellman-group1-sha1 and diffie-hellman-group14-sha1. This causes a NullPointerException as the field being read can only ever by null at this point. This PR modifies Trilead to use a hardcoded reference to `SHA1` at this point since the algorithm can only ever be using SHA1 in this scenario.
=> [JENKINS-44120] Prevent NPE when using DH group 1 or 14 with SHA1 KEX

src/com/trilead/ssh2/SCPClient.java
`SCP` does not seem to have an RFC which generalized for the responses error code, so it seems to depend on each implementation. In any case, `0` seems to mean always operations successful, but the old code does not tell you the error response code in case of failure. 
I don't know too much about `trilead-ssh2`, so the simplification I am doing might be totally wrong.
The goal is to print the error response code under any failure.
A review is appreciated.
```
Oct 13, 2017 3:51:57 PM null 
INFO: Copying slave.jar 
ERROR: Error during SCP transfer. 
java.io.IOException: Error during SCP transfer. 
at com.trilead.ssh2.SCPClient.put(SCPClient.java:523) 
at com.trilead.ssh2.SCPClient.put(SCPClient.java:476) 
at hudson.plugins.ec2.ssh.EC2UnixLauncher.launch(EC2UnixLauncher.java:214) 
at …
```
=> [JENKINS-47603] Just print the SCP response code under failure

src/com/trilead/ssh2/Connection.java
Just caught it in SSH Slaves plugin tests on my local machine: https://issues.jenkins-ci.org/browse/JENKINS-47458
Not sure whether `null` is valid though
@reviewbybees @paladox @mc1arke
=> [JENKINS-47458] - Check for null in Connection#getReasonClosedCause()

src/com/trilead/ssh2/auth/AuthenticationManager.java
[JENKINS-53651](https://issues.jenkins-ci.org/browse/JENKINS-53651)
* Wait a timeout time for packets with size 0
* Use Thread.wait(TIMEOUT) instead Thread.wait()
=> [JENKINS-53651] wait for a timeout time if the packets have 0 size

src/com/trilead/ssh2/LocalPortForwarder.java, src/com/trilead/ssh2/channel/LocalAcceptThread.java
typically allocated from an ephemeral port range
java.net.ServerSocket has support for setting port to 0 and will then
automatically allocate a port.
trilead.LocalPortForwarder handles port 0 fine already however as a end
user its currently not possible to figure out which port was actually
allocated in the end which this fix changes.
=> Support for port=0 which means automatically allocated port.

src/com/trilead/ssh2/channel/ChannelManager.java
Basically solving the similar hanging issues as https://github.com/jenkinsci/trilead-ssh2/pull/6/files
=> Resolve several possible infinite hangings because of wait()

pom.xml, src/com/trilead/ssh2/crypto/PEMDecoder.java, src/com/trilead/ssh2/crypto/cipher/AES.java, src/com/trilead/ssh2/crypto/cipher/BlockCipherFactory.java, src/com/trilead/ssh2/crypto/cipher/BlowFish.java, src/com/trilead/ssh2/crypto/cipher/CBCMode.java, src/com/trilead/ssh2/crypto/cipher/CTRMode.java, src/com/trilead/ssh2/crypto/cipher/DES.java, src/com/trilead/ssh2/crypto/cipher/DESede.java, src/com/trilead/ssh2/crypto/cipher/JreCipherWrapper.java, src/com/trilead/ssh2/signature/OpenSshCertificateDecoder.java, test/com/trilead/ssh2/crypto/cipher/JreCipherWrapperTest.java
This deprecates the included implementations of block ciphers in preference of the ones bundled with the JDK.
Signed-off-by: Matt Sicker <boards@gmail.com>
@jeffret-b @daniel-beck @Wadeck
=> [JENKINS-62552] Use standard crypto APIs

src/com/trilead/ssh2/signature/KeyAlgorithmManager.java, src/com/trilead/ssh2/signature/RSAKeyAlgorithm.java, test/com/trilead/ssh2/KnownHostsTest.java, test/com/trilead/ssh2/signature/RSAKeyAlgorithmTest.java
This adds support for the two new key algorithms specified in RFC 8332: RSA with SHA-256 and SHA-512. These still use the same key format as the SHA-1 variant (ssh-rsa), though the signature names are updated to rsa-sha2-256 and rsa-sha2-512.
Tested with OpenSSH 8.1p1 on macOS and with the Docker images. Locally, I configured sshd to only allow `HostKeyAlgorithms rsa-sha2-512,rsa-sha2-256` which forced the client to use one of the two added algorithms. This worked after I updated my known hosts file accordingly which was previously defaulting to ECDSA (tested with SSH Build Agents plugin in Jenkins master).
Compare to #43 which initially tried to implement this incorrectly.
Signed-off-by: Matt Sicker <boards@gmail.com>
@jeffret-b @Wadeck @daniel-beck
=> [JENKINS-62311] Add support for RFC 8332

Jenkinsfile
The artifacts are not got by the incremental process because are not in the correct place. I cannot use the default implementation of prepareToPublishIncrementals because it gives me the following error due the .m2 folder used is the system .m2 and contains tons of artifacts.
```
22:22:27  Archiving artifacts
22:22:27  java.lang.InterruptedException: no matches found within 10000
22:22:27  	at hudson.FilePath$ValidateAntFileMask.hasMatch(FilePath.java:2865)
22:22:27  	at hudson.FilePath$ValidateAntFileMask.invoke(FilePath.java:2744)
22:22:27  	at hudson.FilePath$ValidateAntFileMask.invoke(FilePath.java:2725)
22:22:27  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3112)
22:22:27  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to EC2 (aws) - High memory ubuntu …
```
=> ci: grab correct incremental artifacts

.gitignore, HISTORY.txt, pom.xml, src/com/trilead/ssh2/ExtendedServerHostKeyVerifier.java, src/com/trilead/ssh2/RandomFactory.java, src/com/trilead/ssh2/crypto/SimpleDERReader.java, src/com/trilead/ssh2/crypto/dh/Curve25519Exchange.java, src/com/trilead/ssh2/crypto/dh/DhExchange.java, src/com/trilead/ssh2/crypto/dh/DhGroupExchange.java, src/com/trilead/ssh2/crypto/dh/EcDhExchange.java, src/com/trilead/ssh2/crypto/dh/GenericDhExchange.java, src/com/trilead/ssh2/packets/PacketKexDHInit.java, src/com/trilead/ssh2/signature/ECDSAKeyAlgorithm.java, src/com/trilead/ssh2/signature/KeyAlgorithm.java, src/com/trilead/ssh2/signature/KeyAlgorithmManager.java, src/com/trilead/ssh2/transport/KexManager.java, src/com/trilead/ssh2/transport/KexState.java, test/com/trilead/ssh2/KnownHostsTest.java, test/com/trilead/ssh2/crypto/SimpleDERReaderTest.java, test/com/trilead/ssh2/crypto/dh/Curve25519ExchangeTest.java, test/com/trilead/ssh2/transport/KexManagerTest.java
Hi
This again add support for kex algorithms:
ecdh-sha2-nistp256 
ecdh-sha2-nistp384
ecdh-sha2-nistp521
curve25519-sha256
I have tested all but curve25519-sha256 vs Mina. 
I tried to keep it as small as possible. Changes taken from connectbot/sshlib.
I also added some more tests from the same project.
@kuisathaverat  I would appreciate if you could do a new check of code.
//mike
=> additional kex algorithms

pom.xml
For a while there are two tests that fail to start the test container ryuk Docker container, this PR is trying to fix it.
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=jenkins/ssh-agent:latest, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
{"message":"No such image: testcontainersofficial/ryuk:0.3.0"}
```
=> test: bump testcontainers version

pom.xml
remove to warning messages from test logs
https://www.slf4j.org/codes.html#StaticLoggerBinder
https://www.slf4j.org/codes.html#no_static_mdc_binder
=> fix: remove slf4j warnings from logs

pom.xml
In my company we use trilead with protobuf-java excluded and it been working fine, (we use all of the KEX algorithms #60 which is the reason why tink was added and indirectly protobuf-java  )
=> Removal of unnecessary protobuf-java

Jenkinsfile, pom.xml, src/spotbugs/excludesFilter.xml
Updates the parent POM and adapts to recent parent POM changes by removing explicit SpotBugs configuration and unnecessary version numbers that are already managed in the parent POM. Rather than solving all SpotBugs violations I simply suppressed any existing violations at the build level so that they do not cause problems for CI runs and that so fixes to particular SpotBugs violations can be tested locally the same way they would be tested in CI.
=> Update parent POM

src/com/trilead/ssh2/transport/TransportManager.java
We ran into an issue were we had hundreds of Trilead threads simply using the default names Thread-1....Thread-250
With this change it would be very easy to identify to what library and connection a thread belongs to.
=> Giving threads names for easier troubleshooting

src/com/trilead/ssh2/Connection.java, src/com/trilead/ssh2/util/TimeoutService.java
See [JENKINS-71798](https://issues.jenkins.io/browse/JENKINS-71798).
Fix has been verified in customers environment
=> JENKINS-71798: TimeoutService threads are left after closing connection

Jenkinsfile, test/com/trilead/ssh2/KnownHostsTest.java
Java 21 released Sep 19, 2023. We'd like to announce full support for Java 21 in early October and would like the most used plugins to be compiling and testing with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
Java 11 will be unsupported by Eclipse Temurin and some other Java providers in October 2024. We'll need to move past Java 11 by that time. It does not change the supported Java version or the byte code that is being generated.
This intentionally does not include Java 11 in the test configuration because Java 11 byte code is being generated by the Java 17 and Java 21 compilation and because Java 11 is being tested at …
=> chore: test and compile with Java 21

src/com/trilead/ssh2/StreamGobbler.java, src/com/trilead/ssh2/auth/AuthenticationManager.java, src/com/trilead/ssh2/channel/ChannelManager.java, src/com/trilead/ssh2/channel/FifoBuffer.java, src/com/trilead/ssh2/transport/KexManager.java, src/com/trilead/ssh2/transport/TransportManager.java
In a couple of important methods the Object.wait() is invoked without any timeout, which in some cases produces threads waiting forever. I've added default timeout of 30mins, in one case of 12h. I'm open to any other timeouts as long as it's not measured in days. It'd be better to have them as some variable as is already done in some cases with e.g.: DEFAULT_WAIT_TIMEOUT, but I left it as just plain values for now, to discuss about the value for the wait(), and then set it as variable.
See [JENKINS-73575](https://issues.jenkins.io/browse/JENKINS-73575).
I believe that when something is wrong with the process it should communicate and not stay in the background wasting resources never to do anything again. This update may create some new issues with regards to problems with agents …
=> Adding timeouts to wait methods, to never allow for infinite wait() state.

src/com/trilead/ssh2/SFTPv3Client.java
Current public APIs for open calls are issued with these flags: SSH_FXF_READ|SSH_FXF_WRITE|SSH_FXF_CREAT|SSH_FXF_TRUNC, i.e. for both reading and writing simultaneously.  due to the way S3 works, this is not feasible to implement it(server) properly, as we would have to store somewhere the whole file being written be able to properly serve the read requests. this could require as much memory or disk volume space as the largest file to be written
I made the existing private method openFile()
public to allow finer control to the few  end users who need it.  
We intend to use it like:
openFile(fileName, 0x00000018 | 0x00000002, attr)
which is the same as existing createFileTruncate but without SSH_FXF_READ
I did not add anything new to be tested, just made a method more accessible.
=> Update SFTPv3Client.java, openFile public
